### ISSUE TITLE
App Ready for Review

### ISSUE THREAD

**Issue by baiIey** [baiIey/ios-tip-calculator#1]
My app is complete, please review. /cc @codepathreview

**Comment by aenean** [comment]
My app is complete, please review. /cc @codepathreview

**Comment by timothy1ee** [comment]
Good work. This prework is a preview of our weekly project process. Generally, weekly projects take between 5-10 hours to complete the required features and an additional 5-10 hours to complete the optional features. In general, we've seen that the more hours you log, the quicker you improve your proficiency with iOS.

The next step is to schedule a brief phone conversation with me [here](https://www.google.com/calendar/selfsched?sstoken=UVBDTi1jVkx4SldqfGRlZmF1bHR8MGVhNTlkZDFmYzQzODdkNDFhZjQ0NWQyZjFiMDU3Nzg). I have appointment slots every week through January 23rd. Admission is rolling, so the sooner you schedule, the better. Once you've selected a time, update the calendar event with a phone number to call you at.

**Comment by baiIey** [comment]
Rock on. I just scheduled an interview for the morning of 16 January, the earliest date available.

Looking forward to speaking with you.
